// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusterHubCommand.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusterHubCommand.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721114053_AddDeviceCallsign")]
    partial class AddDeviceCallsign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.CommandOperator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("CommandOperators");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.CoreDirectorySyncConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastSyncNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CoreDirectorySyncConfigs");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Callsign")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CurrentLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CurrentLongitude")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LocationUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VehicleProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("VehicleProfileId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.EmployeeStationAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHome")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("EmployeeId", "OrgUnitId")
                        .IsUnique();

                    b.ToTable("EmployeeStationAssignments");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("OrganisationId", "ExternalReference")
                        .IsUnique();

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.IncidentAppliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentAppliances");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.IncidentUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UpdateType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentUpdates");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.IntegrationApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("IntegrationApiKeys");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.OrgUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CoreId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrgUnitTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("ltree");

                    b.HasKey("Id");

                    b.HasIndex("OrgUnitTypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path");

                    b.ToTable("OrgUnits");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.OrgUnitType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AllowedParentTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AllowedParentTypeId");

                    b.ToTable("OrgUnitTypes");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.VehicleProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("MaxHeightMetres")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxWeightTonnes")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxWidthMetres")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("VehicleProfiles");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.CommandOperator", b =>
                {
                    b.HasOne("MusterHubCommand.Api.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.Device", b =>
                {
                    b.HasOne("MusterHubCommand.Api.Data.Entities.OrgUnit", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusterHubCommand.Api.Data.Entities.VehicleProfile", "VehicleProfile")
                        .WithMany()
                        .HasForeignKey("VehicleProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OrgUnit");

                    b.Navigation("VehicleProfile");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.EmployeeStationAssignment", b =>
                {
                    b.HasOne("MusterHubCommand.Api.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusterHubCommand.Api.Data.Entities.OrgUnit", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("OrgUnit");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.Incident", b =>
                {
                    b.HasOne("MusterHubCommand.Api.Data.Entities.OrgUnit", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrgUnit");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.IncidentAppliance", b =>
                {
                    b.HasOne("MusterHubCommand.Api.Data.Entities.Incident", "Incident")
                        .WithMany("Appliances")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.IncidentUpdate", b =>
                {
                    b.HasOne("MusterHubCommand.Api.Data.Entities.Incident", "Incident")
                        .WithMany("Updates")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.OrgUnit", b =>
                {
                    b.HasOne("MusterHubCommand.Api.Data.Entities.OrgUnitType", "OrgUnitType")
                        .WithMany()
                        .HasForeignKey("OrgUnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusterHubCommand.Api.Data.Entities.OrgUnit", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrgUnitType");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.OrgUnitType", b =>
                {
                    b.HasOne("MusterHubCommand.Api.Data.Entities.OrgUnitType", "AllowedParentType")
                        .WithMany()
                        .HasForeignKey("AllowedParentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AllowedParentType");
                });

            modelBuilder.Entity("MusterHubCommand.Api.Data.Entities.Incident", b =>
                {
                    b.Navigation("Appliances");

                    b.Navigation("Updates");
                });
#pragma warning restore 612, 618
        }
    }
}
